"""Helpers to run the official harness scorers (with Windows-safe UTF-8) and to audit time leaks."""
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HARNESS = ROOT / "eval_harness"


def run_scorer(script, *args):
    env = dict(os.environ, PYTHONUTF8="1", PYTHONIOENCODING="utf-8")
    p = subprocess.run([sys.executable, str(HARNESS / script), *args], capture_output=True, text=True,
                       encoding="utf-8", env=env, cwd=str(HARNESS))
    return p.stdout + p.stderr


# ---------------------------------------------------------------------------- leak audit
def leak_audit(n_times=25, seed=7, data_dir=None):
    """Independent time-travel audit. For every train question, at many random as_of moments (plus the question's own),
    retrieve and assert: nothing after as_of, nothing deleted, no deletion markers, no secrets in any text shown.
    The oracle is the harness's own record loader, not our store."""
    import random
    from datetime import datetime, timedelta
    sys.path.insert(0, str(HARNESS))
    import records as H            # harness loader = ground truth for delivery times
    from .memory import Memory
    from .safety import has_secret
    from .store import parse_dt

    hu, hdel, _ = H.load(str(data_dir or (ROOT / "data")))
    htime = {u.id: u.time for u in hu}
    m = Memory(data_dir, use_llm=False)
    qs = [json.loads(l) for l in open(ROOT / "evals" / "memory_train.jsonl", encoding="utf-8") if l.strip()]
    rng = random.Random(seed)
    lo, hi = parse_dt("2026-09-01T00:00:00-07:00"), parse_dt("2026-09-19T00:00:00-07:00")
    span = (hi - lo).total_seconds()
    checks, bad = 0, []
    for q in qs:
        times = [parse_dt(q["as_of"])] + [lo + timedelta(seconds=rng.random() * span) for _ in range(n_times)]
        for t in times:
            hits, _ = m.retriever.search(q["question"], t, k=20)
            checks += 1
            for h in hits:
                i = h.unit.id
                if i not in htime:
                    continue        # edit-event ids are our own units of harness records; checked below
                dead = i in hdel and hdel[i] <= t
                if htime[i] > t or dead:
                    bad.append((q["id"], str(t), i, "future" if htime[i] > t else "deleted"))
                if h.unit.kind == "deleted_marker":
                    bad.append((q["id"], str(t), i, "marker"))
                if has_secret(h.text):
                    bad.append((q["id"], str(t), i, "secret"))
    return {"queries": checks, "violations": bad}


# ---------------------------------------------------------------------------- results report
START, END = "<!-- RESULTS:START -->", "<!-- RESULTS:END -->"


def _pct(x):
    if isinstance(x, dict) and "mean" in x:
        lo, hi = x.get("ci95", [None, None])
        ci = f" (95% CI {100 * lo:.0f}%-{100 * hi:.0f}%)" if lo is not None else ""
        return f"{100 * x['mean']:.1f}%{ci}"
    return f"{100 * x:.1f}%" if isinstance(x, (int, float)) and x <= 1.0 else str(x)


def build_report(out_dir=None):
    """Read the scorers' own JSON from out/ and return a markdown results block. Nothing is typed by hand."""
    out = Path(out_dir) if out_dir else ROOT / "out"
    rows = ["| Metric | Result |", "|---|---|"]

    def load(name):
        p = out / name
        return json.loads(p.read_text(encoding="utf-8"))["summary"] if p.exists() else None
    r, m, a = load("retrieval_report.json"), load("memory_report.json"), load("actions_report.json")
    if r:
        rows.append(f"| Retrieval, train (main score) | {_pct(r['score'])} over {r['scored_on_coverage']} scored questions; MRR {r['mrr']}; "
                    f"complete in top 5 {_pct(r['complete_unit@5'])}, top 10 {_pct(r['complete_unit@10'])}; harm-only clean {_pct(r['harm_only_clean@20'])} |")
    if m:
        rows.append(f"| Answers, train (judge: {m['judge']}) | strict {_pct(m['strict'])}, lenient {_pct(m['lenient'])}, hard failures {m['hard_failures']}; "
                    f"source recall {m['source_recall']}, precision {m['source_precision']} |")
    if a:
        rows.append(f"| Actions, train | pass rate {_pct(a['pass_rate'])}, argument accuracy {_pct(a['arg_accuracy'])} (n={a['n']}) |")
    stamp = ""
    return "\n".join(rows)


def write_report(readme=None, out_dir=None):
    block = build_report(out_dir)
    path = Path(readme) if readme else ROOT / "README.md"
    text = path.read_text(encoding="utf-8")
    if START in text and END in text:
        a, b = text.index(START), text.index(END) + len(END)
        text = text[:a] + START + "\n" + block + "\n" + END + text[b:]
        path.write_text(text, encoding="utf-8")
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "RESULTS.md").write_text("# Latest results (generated by `python run.py report`)\n\n" + block + "\n", encoding="utf-8")
    return block
